/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MasterClassesRouteImport } from './routes/master-classes'
import { Route as JuryRouteImport } from './routes/jury'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as ChatSlugRouteImport } from './routes/chat.$slug'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiJuryRouteImport } from './routes/api/jury'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCompetitionsRouteImport } from './routes/api/competitions'
import { Route as ApiApplicationsRouteImport } from './routes/api/applications'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminNewsRouteImport } from './routes/admin_.news'
import { Route as AdminChatRouteImport } from './routes/admin_.chat'
import { Route as ApiPublicSetupAdminsRouteImport } from './routes/api/public/setup-admins'
import { Route as ApiProfilesMeRouteImport } from './routes/api/profiles/me'
import { Route as ApiProfilesAvatarRouteImport } from './routes/api/profiles/avatar'
import { Route as ApiNewsIdRouteImport } from './routes/api/news.$id'
import { Route as ApiMessagesSearchRouteImport } from './routes/api/messages/search'
import { Route as ApiMessagesConversationsRouteImport } from './routes/api/messages/conversations'
import { Route as ApiMessagesConversationIdRouteImport } from './routes/api/messages/$conversationId'
import { Route as ApiChatSlugRouteImport } from './routes/api/chat.$slug'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSigninRouteImport } from './routes/api/auth/signin'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthChangeEmailRouteImport } from './routes/api/auth/change-email'
import { Route as ApiApplicationsIdRouteImport } from './routes/api/applications.$id'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminNewsRouteImport } from './routes/api/admin/news'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiProfilesAvatarUserIdRouteImport } from './routes/api/profiles/avatar.$userId'
import { Route as ApiFilesNewsNewsIdRouteImport } from './routes/api/files/news.$newsId'
import { Route as ApiFilesChatMessageIdRouteImport } from './routes/api/files/chat.$messageId'
import { Route as ApiAuthResetPasswordConfirmRouteImport } from './routes/api/auth/reset-password.confirm'
import { Route as ApiAdminNewsIdRouteImport } from './routes/api/admin/news.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterClassesRoute = MasterClassesRouteImport.update({
  id: '/master-classes',
  path: '/master-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const JuryRoute = JuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitionsRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompetitionsRoute,
} as any)
const ChatSlugRoute = ChatSlugRouteImport.update({
  id: '/chat/$slug',
  path: '/chat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApplyRoute,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJuryRoute = ApiJuryRouteImport.update({
  id: '/api/jury',
  path: '/api/jury',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitionsRoute = ApiCompetitionsRouteImport.update({
  id: '/api/competitions',
  path: '/api/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsRoute = ApiApplicationsRouteImport.update({
  id: '/api/applications',
  path: '/api/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin_/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin_/chat',
  path: '/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminsRoute = ApiPublicSetupAdminsRouteImport.update({
  id: '/api/public/setup-admins',
  path: '/api/public/setup-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesMeRoute = ApiProfilesMeRouteImport.update({
  id: '/api/profiles/me',
  path: '/api/profiles/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesAvatarRoute = ApiProfilesAvatarRouteImport.update({
  id: '/api/profiles/avatar',
  path: '/api/profiles/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsIdRoute = ApiNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiMessagesSearchRoute = ApiMessagesSearchRouteImport.update({
  id: '/api/messages/search',
  path: '/api/messages/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesConversationsRoute =
  ApiMessagesConversationsRouteImport.update({
    id: '/api/messages/conversations',
    path: '/api/messages/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMessagesConversationIdRoute =
  ApiMessagesConversationIdRouteImport.update({
    id: '/api/messages/$conversationId',
    path: '/api/messages/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatSlugRoute = ApiChatSlugRouteImport.update({
  id: '/api/chat/$slug',
  path: '/api/chat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangeEmailRoute = ApiAuthChangeEmailRouteImport.update({
  id: '/api/auth/change-email',
  path: '/api/auth/change-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsIdRoute = ApiApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiApplicationsRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNewsRoute = ApiAdminNewsRouteImport.update({
  id: '/api/admin/news',
  path: '/api/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesAvatarUserIdRoute = ApiProfilesAvatarUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiProfilesAvatarRoute,
} as any)
const ApiFilesNewsNewsIdRoute = ApiFilesNewsNewsIdRouteImport.update({
  id: '/api/files/news/$newsId',
  path: '/api/files/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesChatMessageIdRoute = ApiFilesChatMessageIdRouteImport.update({
  id: '/api/files/chat/$messageId',
  path: '/api/files/chat/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordConfirmRoute =
  ApiAuthResetPasswordConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => ApiAuthResetPasswordRoute,
  } as any)
const ApiAdminNewsIdRoute = ApiAdminNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/jury': typeof JuryRoute
  '/master-classes': typeof MasterClassesRoute
  '/messages': typeof MessagesRoute
  '/my-applications': typeof MyApplicationsRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/applications': typeof ApiApplicationsRouteWithChildren
  '/api/competitions': typeof ApiCompetitionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jury': typeof ApiJuryRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/news': typeof ApiAdminNewsRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/applications/$id': typeof ApiApplicationsIdRoute
  '/api/auth/change-email': typeof ApiAuthChangeEmailRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/chat/$slug': typeof ApiChatSlugRoute
  '/api/messages/$conversationId': typeof ApiMessagesConversationIdRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/search': typeof ApiMessagesSearchRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/profiles/avatar': typeof ApiProfilesAvatarRouteWithChildren
  '/api/profiles/me': typeof ApiProfilesMeRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
  '/api/admin/news/$id': typeof ApiAdminNewsIdRoute
  '/api/auth/reset-password/confirm': typeof ApiAuthResetPasswordConfirmRoute
  '/api/files/chat/$messageId': typeof ApiFilesChatMessageIdRoute
  '/api/files/news/$newsId': typeof ApiFilesNewsNewsIdRoute
  '/api/profiles/avatar/$userId': typeof ApiProfilesAvatarUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/jury': typeof JuryRoute
  '/master-classes': typeof MasterClassesRoute
  '/messages': typeof MessagesRoute
  '/my-applications': typeof MyApplicationsRoute
  '/partners': typeof PartnersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/applications': typeof ApiApplicationsRouteWithChildren
  '/api/competitions': typeof ApiCompetitionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jury': typeof ApiJuryRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/news': typeof ApiAdminNewsRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/applications/$id': typeof ApiApplicationsIdRoute
  '/api/auth/change-email': typeof ApiAuthChangeEmailRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/chat/$slug': typeof ApiChatSlugRoute
  '/api/messages/$conversationId': typeof ApiMessagesConversationIdRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/search': typeof ApiMessagesSearchRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/profiles/avatar': typeof ApiProfilesAvatarRouteWithChildren
  '/api/profiles/me': typeof ApiProfilesMeRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
  '/api/admin/news/$id': typeof ApiAdminNewsIdRoute
  '/api/auth/reset-password/confirm': typeof ApiAuthResetPasswordConfirmRoute
  '/api/files/chat/$messageId': typeof ApiFilesChatMessageIdRoute
  '/api/files/news/$newsId': typeof ApiFilesNewsNewsIdRoute
  '/api/profiles/avatar/$userId': typeof ApiProfilesAvatarUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/jury': typeof JuryRoute
  '/master-classes': typeof MasterClassesRoute
  '/messages': typeof MessagesRoute
  '/my-applications': typeof MyApplicationsRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin_/chat': typeof AdminChatRoute
  '/admin_/news': typeof AdminNewsRoute
  '/admin_/users': typeof AdminUsersRoute
  '/api/applications': typeof ApiApplicationsRouteWithChildren
  '/api/competitions': typeof ApiCompetitionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jury': typeof ApiJuryRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/news': typeof ApiAdminNewsRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/applications/$id': typeof ApiApplicationsIdRoute
  '/api/auth/change-email': typeof ApiAuthChangeEmailRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/chat/$slug': typeof ApiChatSlugRoute
  '/api/messages/$conversationId': typeof ApiMessagesConversationIdRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/search': typeof ApiMessagesSearchRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/profiles/avatar': typeof ApiProfilesAvatarRouteWithChildren
  '/api/profiles/me': typeof ApiProfilesMeRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
  '/api/admin/news/$id': typeof ApiAdminNewsIdRoute
  '/api/auth/reset-password/confirm': typeof ApiAuthResetPasswordConfirmRoute
  '/api/files/chat/$messageId': typeof ApiFilesChatMessageIdRoute
  '/api/files/news/$newsId': typeof ApiFilesNewsNewsIdRoute
  '/api/profiles/avatar/$userId': typeof ApiProfilesAvatarUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/competitions'
    | '/contacts'
    | '/history'
    | '/jury'
    | '/master-classes'
    | '/messages'
    | '/my-applications'
    | '/news'
    | '/partners'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/admin/chat'
    | '/admin/news'
    | '/admin/users'
    | '/api/applications'
    | '/api/competitions'
    | '/api/health'
    | '/api/jury'
    | '/api/news'
    | '/apply/$slug'
    | '/chat/$slug'
    | '/competitions/$slug'
    | '/news/$id'
    | '/competitions/'
    | '/news/'
    | '/api/admin/dashboard'
    | '/api/admin/news'
    | '/api/admin/users'
    | '/api/applications/$id'
    | '/api/auth/change-email'
    | '/api/auth/change-password'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/chat/$slug'
    | '/api/messages/$conversationId'
    | '/api/messages/conversations'
    | '/api/messages/search'
    | '/api/news/$id'
    | '/api/profiles/avatar'
    | '/api/profiles/me'
    | '/api/public/setup-admins'
    | '/api/admin/news/$id'
    | '/api/auth/reset-password/confirm'
    | '/api/files/chat/$messageId'
    | '/api/files/news/$newsId'
    | '/api/profiles/avatar/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/contacts'
    | '/history'
    | '/jury'
    | '/master-classes'
    | '/messages'
    | '/my-applications'
    | '/partners'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/admin/chat'
    | '/admin/news'
    | '/admin/users'
    | '/api/applications'
    | '/api/competitions'
    | '/api/health'
    | '/api/jury'
    | '/api/news'
    | '/apply/$slug'
    | '/chat/$slug'
    | '/competitions/$slug'
    | '/news/$id'
    | '/competitions'
    | '/news'
    | '/api/admin/dashboard'
    | '/api/admin/news'
    | '/api/admin/users'
    | '/api/applications/$id'
    | '/api/auth/change-email'
    | '/api/auth/change-password'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/chat/$slug'
    | '/api/messages/$conversationId'
    | '/api/messages/conversations'
    | '/api/messages/search'
    | '/api/news/$id'
    | '/api/profiles/avatar'
    | '/api/profiles/me'
    | '/api/public/setup-admins'
    | '/api/admin/news/$id'
    | '/api/auth/reset-password/confirm'
    | '/api/files/chat/$messageId'
    | '/api/files/news/$newsId'
    | '/api/profiles/avatar/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/competitions'
    | '/contacts'
    | '/history'
    | '/jury'
    | '/master-classes'
    | '/messages'
    | '/my-applications'
    | '/news'
    | '/partners'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/admin_/chat'
    | '/admin_/news'
    | '/admin_/users'
    | '/api/applications'
    | '/api/competitions'
    | '/api/health'
    | '/api/jury'
    | '/api/news'
    | '/apply/$slug'
    | '/chat/$slug'
    | '/competitions/$slug'
    | '/news/$id'
    | '/competitions/'
    | '/news/'
    | '/api/admin/dashboard'
    | '/api/admin/news'
    | '/api/admin/users'
    | '/api/applications/$id'
    | '/api/auth/change-email'
    | '/api/auth/change-password'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/chat/$slug'
    | '/api/messages/$conversationId'
    | '/api/messages/conversations'
    | '/api/messages/search'
    | '/api/news/$id'
    | '/api/profiles/avatar'
    | '/api/profiles/me'
    | '/api/public/setup-admins'
    | '/api/admin/news/$id'
    | '/api/auth/reset-password/confirm'
    | '/api/files/chat/$messageId'
    | '/api/files/news/$newsId'
    | '/api/profiles/avatar/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  HistoryRoute: typeof HistoryRoute
  JuryRoute: typeof JuryRoute
  MasterClassesRoute: typeof MasterClassesRoute
  MessagesRoute: typeof MessagesRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  NewsRoute: typeof NewsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiApplicationsRoute: typeof ApiApplicationsRouteWithChildren
  ApiCompetitionsRoute: typeof ApiCompetitionsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJuryRoute: typeof ApiJuryRoute
  ApiNewsRoute: typeof ApiNewsRouteWithChildren
  ChatSlugRoute: typeof ChatSlugRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminNewsRoute: typeof ApiAdminNewsRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthChangeEmailRoute: typeof ApiAuthChangeEmailRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRouteWithChildren
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiChatSlugRoute: typeof ApiChatSlugRoute
  ApiMessagesConversationIdRoute: typeof ApiMessagesConversationIdRoute
  ApiMessagesConversationsRoute: typeof ApiMessagesConversationsRoute
  ApiMessagesSearchRoute: typeof ApiMessagesSearchRoute
  ApiProfilesAvatarRoute: typeof ApiProfilesAvatarRouteWithChildren
  ApiProfilesMeRoute: typeof ApiProfilesMeRoute
  ApiPublicSetupAdminsRoute: typeof ApiPublicSetupAdminsRoute
  ApiFilesChatMessageIdRoute: typeof ApiFilesChatMessageIdRoute
  ApiFilesNewsNewsIdRoute: typeof ApiFilesNewsNewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-classes': {
      id: '/master-classes'
      path: '/master-classes'
      fullPath: '/master-classes'
      preLoaderRoute: typeof MasterClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jury': {
      id: '/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof JuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/chat/$slug': {
      id: '/chat/$slug'
      path: '/chat/$slug'
      fullPath: '/chat/$slug'
      preLoaderRoute: typeof ChatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jury': {
      id: '/api/jury'
      path: '/api/jury'
      fullPath: '/api/jury'
      preLoaderRoute: typeof ApiJuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitions': {
      id: '/api/competitions'
      path: '/api/competitions'
      fullPath: '/api/competitions'
      preLoaderRoute: typeof ApiCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications': {
      id: '/api/applications'
      path: '/api/applications'
      fullPath: '/api/applications'
      preLoaderRoute: typeof ApiApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/news': {
      id: '/admin_/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/chat': {
      id: '/admin_/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admins': {
      id: '/api/public/setup-admins'
      path: '/api/public/setup-admins'
      fullPath: '/api/public/setup-admins'
      preLoaderRoute: typeof ApiPublicSetupAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/me': {
      id: '/api/profiles/me'
      path: '/api/profiles/me'
      fullPath: '/api/profiles/me'
      preLoaderRoute: typeof ApiProfilesMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/avatar': {
      id: '/api/profiles/avatar'
      path: '/api/profiles/avatar'
      fullPath: '/api/profiles/avatar'
      preLoaderRoute: typeof ApiProfilesAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/$id': {
      id: '/api/news/$id'
      path: '/$id'
      fullPath: '/api/news/$id'
      preLoaderRoute: typeof ApiNewsIdRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/messages/search': {
      id: '/api/messages/search'
      path: '/api/messages/search'
      fullPath: '/api/messages/search'
      preLoaderRoute: typeof ApiMessagesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/conversations': {
      id: '/api/messages/conversations'
      path: '/api/messages/conversations'
      fullPath: '/api/messages/conversations'
      preLoaderRoute: typeof ApiMessagesConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$conversationId': {
      id: '/api/messages/$conversationId'
      path: '/api/messages/$conversationId'
      fullPath: '/api/messages/$conversationId'
      preLoaderRoute: typeof ApiMessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$slug': {
      id: '/api/chat/$slug'
      path: '/api/chat/$slug'
      fullPath: '/api/chat/$slug'
      preLoaderRoute: typeof ApiChatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-email': {
      id: '/api/auth/change-email'
      path: '/api/auth/change-email'
      fullPath: '/api/auth/change-email'
      preLoaderRoute: typeof ApiAuthChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications/$id': {
      id: '/api/applications/$id'
      path: '/$id'
      fullPath: '/api/applications/$id'
      preLoaderRoute: typeof ApiApplicationsIdRouteImport
      parentRoute: typeof ApiApplicationsRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/news': {
      id: '/api/admin/news'
      path: '/api/admin/news'
      fullPath: '/api/admin/news'
      preLoaderRoute: typeof ApiAdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/avatar/$userId': {
      id: '/api/profiles/avatar/$userId'
      path: '/$userId'
      fullPath: '/api/profiles/avatar/$userId'
      preLoaderRoute: typeof ApiProfilesAvatarUserIdRouteImport
      parentRoute: typeof ApiProfilesAvatarRoute
    }
    '/api/files/news/$newsId': {
      id: '/api/files/news/$newsId'
      path: '/api/files/news/$newsId'
      fullPath: '/api/files/news/$newsId'
      preLoaderRoute: typeof ApiFilesNewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/chat/$messageId': {
      id: '/api/files/chat/$messageId'
      path: '/api/files/chat/$messageId'
      fullPath: '/api/files/chat/$messageId'
      preLoaderRoute: typeof ApiFilesChatMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password/confirm': {
      id: '/api/auth/reset-password/confirm'
      path: '/confirm'
      fullPath: '/api/auth/reset-password/confirm'
      preLoaderRoute: typeof ApiAuthResetPasswordConfirmRouteImport
      parentRoute: typeof ApiAuthResetPasswordRoute
    }
    '/api/admin/news/$id': {
      id: '/api/admin/news/$id'
      path: '/$id'
      fullPath: '/api/admin/news/$id'
      preLoaderRoute: typeof ApiAdminNewsIdRouteImport
      parentRoute: typeof ApiAdminNewsRoute
    }
  }
}

interface ApplyRouteChildren {
  ApplySlugRoute: typeof ApplySlugRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplySlugRoute: ApplySlugRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface CompetitionsRouteChildren {
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ApiApplicationsRouteChildren {
  ApiApplicationsIdRoute: typeof ApiApplicationsIdRoute
}

const ApiApplicationsRouteChildren: ApiApplicationsRouteChildren = {
  ApiApplicationsIdRoute: ApiApplicationsIdRoute,
}

const ApiApplicationsRouteWithChildren = ApiApplicationsRoute._addFileChildren(
  ApiApplicationsRouteChildren,
)

interface ApiNewsRouteChildren {
  ApiNewsIdRoute: typeof ApiNewsIdRoute
}

const ApiNewsRouteChildren: ApiNewsRouteChildren = {
  ApiNewsIdRoute: ApiNewsIdRoute,
}

const ApiNewsRouteWithChildren =
  ApiNewsRoute._addFileChildren(ApiNewsRouteChildren)

interface ApiAdminNewsRouteChildren {
  ApiAdminNewsIdRoute: typeof ApiAdminNewsIdRoute
}

const ApiAdminNewsRouteChildren: ApiAdminNewsRouteChildren = {
  ApiAdminNewsIdRoute: ApiAdminNewsIdRoute,
}

const ApiAdminNewsRouteWithChildren = ApiAdminNewsRoute._addFileChildren(
  ApiAdminNewsRouteChildren,
)

interface ApiAuthResetPasswordRouteChildren {
  ApiAuthResetPasswordConfirmRoute: typeof ApiAuthResetPasswordConfirmRoute
}

const ApiAuthResetPasswordRouteChildren: ApiAuthResetPasswordRouteChildren = {
  ApiAuthResetPasswordConfirmRoute: ApiAuthResetPasswordConfirmRoute,
}

const ApiAuthResetPasswordRouteWithChildren =
  ApiAuthResetPasswordRoute._addFileChildren(ApiAuthResetPasswordRouteChildren)

interface ApiProfilesAvatarRouteChildren {
  ApiProfilesAvatarUserIdRoute: typeof ApiProfilesAvatarUserIdRoute
}

const ApiProfilesAvatarRouteChildren: ApiProfilesAvatarRouteChildren = {
  ApiProfilesAvatarUserIdRoute: ApiProfilesAvatarUserIdRoute,
}

const ApiProfilesAvatarRouteWithChildren =
  ApiProfilesAvatarRoute._addFileChildren(ApiProfilesAvatarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRouteWithChildren,
  AuthRoute: AuthRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  ContactsRoute: ContactsRoute,
  HistoryRoute: HistoryRoute,
  JuryRoute: JuryRoute,
  MasterClassesRoute: MasterClassesRoute,
  MessagesRoute: MessagesRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  NewsRoute: NewsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminChatRoute: AdminChatRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiApplicationsRoute: ApiApplicationsRouteWithChildren,
  ApiCompetitionsRoute: ApiCompetitionsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJuryRoute: ApiJuryRoute,
  ApiNewsRoute: ApiNewsRouteWithChildren,
  ChatSlugRoute: ChatSlugRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminNewsRoute: ApiAdminNewsRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthChangeEmailRoute: ApiAuthChangeEmailRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRouteWithChildren,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiChatSlugRoute: ApiChatSlugRoute,
  ApiMessagesConversationIdRoute: ApiMessagesConversationIdRoute,
  ApiMessagesConversationsRoute: ApiMessagesConversationsRoute,
  ApiMessagesSearchRoute: ApiMessagesSearchRoute,
  ApiProfilesAvatarRoute: ApiProfilesAvatarRouteWithChildren,
  ApiProfilesMeRoute: ApiProfilesMeRoute,
  ApiPublicSetupAdminsRoute: ApiPublicSetupAdminsRoute,
  ApiFilesChatMessageIdRoute: ApiFilesChatMessageIdRoute,
  ApiFilesNewsNewsIdRoute: ApiFilesNewsNewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
