/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MasterClassesRouteImport } from './routes/master-classes'
import { Route as JuryRouteImport } from './routes/jury'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as ChatSlugRouteImport } from './routes/chat.$slug'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminChatRouteImport } from './routes/admin_.chat'
import { Route as ApiPublicSetupAdminsRouteImport } from './routes/api/public/setup-admins'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterClassesRoute = MasterClassesRouteImport.update({
  id: '/master-classes',
  path: '/master-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const JuryRoute = JuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompetitionsRoute,
} as any)
const ChatSlugRoute = ChatSlugRouteImport.update({
  id: '/chat/$slug',
  path: '/chat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApplyRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin_/chat',
  path: '/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminsRoute = ApiPublicSetupAdminsRouteImport.update({
  id: '/api/public/setup-admins',
  path: '/api/public/setup-admins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/jury': typeof JuryRoute
  '/master-classes': typeof MasterClassesRoute
  '/messages': typeof MessagesRoute
  '/my-applications': typeof MyApplicationsRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/jury': typeof JuryRoute
  '/master-classes': typeof MasterClassesRoute
  '/messages': typeof MessagesRoute
  '/my-applications': typeof MyApplicationsRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/jury': typeof JuryRoute
  '/master-classes': typeof MasterClassesRoute
  '/messages': typeof MessagesRoute
  '/my-applications': typeof MyApplicationsRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin_/chat': typeof AdminChatRoute
  '/admin_/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/competitions'
    | '/contacts'
    | '/history'
    | '/jury'
    | '/master-classes'
    | '/messages'
    | '/my-applications'
    | '/news'
    | '/partners'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/admin/chat'
    | '/admin/users'
    | '/api/health'
    | '/apply/$slug'
    | '/chat/$slug'
    | '/competitions/$slug'
    | '/api/public/setup-admins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/competitions'
    | '/contacts'
    | '/history'
    | '/jury'
    | '/master-classes'
    | '/messages'
    | '/my-applications'
    | '/news'
    | '/partners'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/admin/chat'
    | '/admin/users'
    | '/api/health'
    | '/apply/$slug'
    | '/chat/$slug'
    | '/competitions/$slug'
    | '/api/public/setup-admins'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/competitions'
    | '/contacts'
    | '/history'
    | '/jury'
    | '/master-classes'
    | '/messages'
    | '/my-applications'
    | '/news'
    | '/partners'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/admin_/chat'
    | '/admin_/users'
    | '/api/health'
    | '/apply/$slug'
    | '/chat/$slug'
    | '/competitions/$slug'
    | '/api/public/setup-admins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  HistoryRoute: typeof HistoryRoute
  JuryRoute: typeof JuryRoute
  MasterClassesRoute: typeof MasterClassesRoute
  MessagesRoute: typeof MessagesRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  NewsRoute: typeof NewsRoute
  PartnersRoute: typeof PartnersRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ChatSlugRoute: typeof ChatSlugRoute
  ApiPublicSetupAdminsRoute: typeof ApiPublicSetupAdminsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-classes': {
      id: '/master-classes'
      path: '/master-classes'
      fullPath: '/master-classes'
      preLoaderRoute: typeof MasterClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jury': {
      id: '/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof JuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/chat/$slug': {
      id: '/chat/$slug'
      path: '/chat/$slug'
      fullPath: '/chat/$slug'
      preLoaderRoute: typeof ChatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/chat': {
      id: '/admin_/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admins': {
      id: '/api/public/setup-admins'
      path: '/api/public/setup-admins'
      fullPath: '/api/public/setup-admins'
      preLoaderRoute: typeof ApiPublicSetupAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApplyRouteChildren {
  ApplySlugRoute: typeof ApplySlugRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplySlugRoute: ApplySlugRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface CompetitionsRouteChildren {
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsSlugRoute: CompetitionsSlugRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRouteWithChildren,
  AuthRoute: AuthRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  ContactsRoute: ContactsRoute,
  HistoryRoute: HistoryRoute,
  JuryRoute: JuryRoute,
  MasterClassesRoute: MasterClassesRoute,
  MessagesRoute: MessagesRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  NewsRoute: NewsRoute,
  PartnersRoute: PartnersRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminChatRoute: AdminChatRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ChatSlugRoute: ChatSlugRoute,
  ApiPublicSetupAdminsRoute: ApiPublicSetupAdminsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
